---
name: Continuous Integration

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, reopened, synchronize]
    merge_group:

jobs:
    static-code-analysis:
        name: Static code analysis
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v6
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version-file: '.node-version'
            - name: Install dependencies
              run: npm clean-install
            - name: Run all tests
              run: npx just test
            - name: Run packtory dry-run
              env:
                  NPM_TOKEN: dry-run
              run: npx packtory publish
